'name': 'cluster_zapi_to_rest_u-01',
 'obj_id': 'vm-8626',
 'state': 'poweredon',
 'vm_uid': '5016f6ae-4c56-8803-ead0-75f94f66f407'}, {'host_id': 'sdot-smicro-009.gdl.englab.netapp.com',
 'hw_version': 'vmx-14',
 'metadata': {'cluster_uuid': '22723022-70a5-11ed-a778-000c297a9d59',
              'node_uuid': '2273752c-70a5-11ed-a778-000c297a9d59'},
 'mgmt_server_uid': '3025b4b7-b510-4852-98ed-38668b194b85',
 'name': 'test-cluster-dns-01',
 'obj_id': 'vm-8784',
 'state': 'poweredon',
 'vm_uid': '5016667c-c755-52e8-d65c-e7bc43af8405'}, {'host_id': 'sdot-smicro-009.gdl.englab.netapp.com',
 'hw_version': 'vmx-14',
 'metadata': {'cluster_uuid': '4dc8066e-711a-11ed-b035-000c297a9d59',
              'node_uuid': '4dc92e5e-711a-11ed-b035-000c297a9d59'},
 'mgmt_server_uid': '3025b4b7-b510-4852-98ed-38668b194b85',
 'name': 'test-set-dns-rest-01',
 'obj_id': 'vm-8803',
 'state': 'poweredoff',
 'vm_uid': '50162132-1f90-f5dd-fe82-24c0826e75d6'}]
2022-12-15 08:02:49,797|DEBUG|27694|5103|logger.py|132|node.py|1578:get_vm_name_from_host| Node [test-cluster-dns-01] Cluster [test-cluster-dns]: found VM 'test-cluster-dns-01' for node on host 'sdot-smicro-009.gdl.englab.netapp.com'
2022-12-15 08:02:49,798| INFO|27694|5103|logger.py|132|cluster_tasks.py|1164:refresh_cluster| Cluster [test-cluster-dns]: node: test-cluster-dns-01 will be refreshed.
2022-12-15 08:02:49,800| INFO|27694|5103|logger.py|132|cluster_tasks.py|1201:refresh_cluster| Cluster [test-cluster-dns]: Testing availability of the ONTAP cluster with management IP address: 10.232.27.158
2022-12-15 08:02:49,863|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "cluster-identity-get"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:02:49,868|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|225:z_get_cluster_identity| Cluster [test-cluster-dns]: got cluster_identity: [{'cluster-contact': None, 'cluster-location': None, 'cluster-name': 'test-cluster-dns', 'cluster-serial-number': '1-80-000011', 'cluster-uuid': '22723022-70a5-11ed-a778-000c297a9d59', 'rdb-uuid': 'c05e814e-70a5-11ed-b3b9-00a0b8cbd853'}]
2022-12-15 08:02:49,921|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "net-interface-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:02:49,947|DEBUG|27694|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:02:49,948|DEBUG|27694|0|coroutine.py|190|Registered Myself: current tasks [{140706895530456: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140706895531000: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2022-12-15 08:02:49,951| INFO|27694|5108|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/dd8fffd8-7c4e-11ed-af6c-000c297a9d59?fields=*,last_modified,message
2022-12-15 08:02:49,953| INFO|27694|5108|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/dd8fffd8-7c4e-11ed-af6c-000c297a9d59?fields=*,last_modified,message returned in 4ms with status HTTPStatus.OK (BA)
2022-12-15 08:02:49,984|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "net-routes-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:02:50,026|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "net-dns-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:02:50,067|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "ntp-server-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:02:50,070| INFO|27694|5103|logger.py|132|cluster.py|3348:patch_cluster_management_network| Cluster [test-cluster-dns]: cluster management network information refreshed
2022-12-15 08:02:50,105|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "cluster-identity-get"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:02:50,108|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|225:z_get_cluster_identity| Cluster [test-cluster-dns]: got cluster_identity: [{'cluster-contact': None, 'cluster-location': None, 'cluster-name': 'test-cluster-dns', 'cluster-serial-number': '1-80-000011', 'cluster-uuid': '22723022-70a5-11ed-a778-000c297a9d59', 'rdb-uuid': 'c05e814e-70a5-11ed-b3b9-00a0b8cbd853'}]
2022-12-15 08:02:58,670|DEBUG|27694|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:02:58,671|DEBUG|27694|0|coroutine.py|190|Registered Myself: current tasks [{140706895530456: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140706889671000: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2022-12-15 08:02:58,674| INFO|27694|5109|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/dd8fffd8-7c4e-11ed-af6c-000c297a9d59?fields=*,last_modified,message
2022-12-15 08:02:58,676| INFO|27694|5109|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/dd8fffd8-7c4e-11ed-af6c-000c297a9d59?fields=*,last_modified,message returned in 4ms with status HTTPStatus.OK (BA)
2022-12-15 08:03:26,790|DEBUG|27694|5103|logger.py|132|ClusterRestApis.py|907:r_system_cli_version| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/private/cli/version?node=*&fields=version" response: {
  "records": [
    {
      "node": "test-cluster-dns-01",
      "version": "NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022"
    }
  ],
  "num_records": 1
}
2022-12-15 08:04:09,728|DEBUG|27694|5103|logger.py|132|ClusterRestApis.py|913:r_system_cli_version| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/private/cli/version?node=*&fields=version" system CLI node version: 1 entry was acted on.

Node: test-cluster-dns-01
NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022
2022-12-15 08:05:32,246|DEBUG|27694|0|coroutine.py|190|Registered Myself: current tasks [{140706895530456: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140706889671000: <CoroutineRecord (asynchronous.crontab:create_mediator) [ACTIVE]>}]
2022-12-15 08:05:32,274|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "cluster-identity-get"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:05:32,275|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|225:z_get_cluster_identity| Cluster [test-cluster-dns]: got cluster_identity: [{'cluster-contact': None, 'cluster-location': None, 'cluster-name': 'test-cluster-dns', 'cluster-serial-number': '1-80-000011', 'cluster-uuid': '22723022-70a5-11ed-a778-000c297a9d59', 'rdb-uuid': 'c05e814e-70a5-11ed-b3b9-00a0b8cbd853'}]
2022-12-15 08:05:34,689|DEBUG|27694|5103|fault.py|147|Unable to find a registered fault for zapi.system_node_get_iter.
2022-12-15 08:05:34,723|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "system-node-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:05:34,725|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|245:z_system_node_get_iter| Cluster [test-cluster-dns]: got system node get iter: [[{'cpu-busytime': '489', 'env-failed-fan-count': '0', 'env-failed-fan-message': 'There are no failed fans.', 'env-failed-power-supply-count': '0', 'env-failed-power-supply-message': 'There are no failed power supplies.', 'env-over-temperature': 'false', 'is-all-flash-optimized': 'false', 'is-all-flash-select-optimized': 'false', 'is-capacity-optimized': 'false', 'is-cloud-optimized': 'false', 'is-diff-svcs': 'false', 'is-epsilon-node': 'true', 'is-node-cluster-eligible': 'true', 'is-node-healthy': 'true', 'is-perf-optimized': 'false', 'maximum-aggregate-size': '219902325555200', 'maximum-number-of-volumes': '1000', 'maximum-volume-size': '329853488332800', 'node': 'test-cluster-dns-01', 'node-location': None, 'node-model': 'FDvM300', 'node-nvram-id': '2443885337', 'node-owner': None, 'node-serial-number': '99887766554433221125', 'node-storage-configuration': 'unknown', 'node-system-id': '2443885337', 'node-uptime': '16433', 'node-uuid': '2273752c-70a5-11ed-a778-000c297a9d59', 'node-vendor': 'NetApp', 'nvram-battery-status': 'battery_ok', 'product-version': 'NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022', 'sas2-sas3-mixed-stack-support': 'none', 'vmhost-info': {'vm-uuid': '42163f4e-cda3-f86d-770f-fb7b9a23caa6', 'vmhost-error': 'Failed to connnect to the vSphere server. Reason: Either the server hostname or IP address is not set, or there are network issues. Correct the vSphere credentials with the "system node virtual-machine hypervisor modify-credentials" command.', 'vmhost-hardware-vendor': 'VMware, Inc.', 'vmhost-model': 'VMware Virtual Platform', 'vmhost-software-vendor': 'NetApp'}}]]
2022-12-15 08:05:34,748|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "cluster-identity-get"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:05:34,750|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|225:z_get_cluster_identity| Cluster [test-cluster-dns]: got cluster_identity: [{'cluster-contact': None, 'cluster-location': None, 'cluster-name': 'test-cluster-dns', 'cluster-serial-number': '1-80-000011', 'cluster-uuid': '22723022-70a5-11ed-a778-000c297a9d59', 'rdb-uuid': 'c05e814e-70a5-11ed-b3b9-00a0b8cbd853'}]
2022-12-15 08:05:34,752| INFO|27694|5103|logger.py|132|cluster.py|3522:patch_cluster_identity| Cluster [test-cluster-dns]: cluster's node count validation successful
2022-12-15 08:05:34,753| INFO|27694|5103|logger.py|132|cluster.py|3533:patch_cluster_identity| Cluster [test-cluster-dns]: cluster identity refreshed
2022-12-15 08:05:45,786| INFO|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "system-cli"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:05:50,093|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|930:z_system_cli_version| Cluster [test-cluster-dns]: System CLI, version: 1 entry was acted on.

Node: test-cluster-dns-01
NetApp Release devN_221108_0200: Tue Nov  8 02:42:19 EST 2022   <1>
2022-12-15 08:06:24,191| INFO|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "system-get-version"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:06:24,193|DEBUG|27694|5103|logger.py|132|ClusterZapis.py|846:z_system_get_version| Cluster [test-cluster-dns]: system get version {'generation': '9', 'major': '13', 'minor': '0'}
2022-12-15 08:06:24,204|DEBUG|27694|5103|fault.py|147|Unable to find a registered fault for zapi.system_node_get_iter.
2022-12-15 08:06:24,231|DEBUG|27694|5103|logger.py|132|ZAPI.py|241:invoke|
API: "system-node-get-iter"
User: "admin"


################# Failed to get system cli Version ########################
}
2022-12-15 08:21:04,691|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|586:r_get_network_routes| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/network/ip/routes/?fields=**" net_routes_info: {'address-family': 'ipv4', 'destination': '0.0.0.0/0', 'gateway': '10.232.27.1', 'metric': 10}
2022-12-15 08:21:04,829|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|658:r_get_dns| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/name-services/dns/?fields=**" response: {
  "records": [
    {
      "svm": {
        "uuid": "c9ef6dfa-70a5-11ed-b3b9-00a0b8cbd853",
        "name": "test-cluster-dns",
        "_links": {
          "self": {
            "href": "/api/svm/svms/c9ef6dfa-70a5-11ed-b3b9-00a0b8cbd853"
          }
        }
      },
      "domains": [
        "gdl.englab.netapp.com"
      ],
      "servers": [
        "10.224.223.135"
      ],
      "timeout": 2,
      "attempts": 1,
      "tld_query_enabled": true,
      "source_address_match": true,
      "packet_query_match": true,
      "scope": "cluster",
      "status": [
        {
          "name_server": "10.224.223.135",
          "state": "up",
          "message": "Response time (msec): 74",
          "code": 0
        }
      ],
      "_links": {
        "self": {
          "href": "/api/name-services/dns/c9ef6dfa-70a5-11ed-b3b9-00a0b8cbd853?fields=**"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/name-services/dns/?fields=%2A%2A"
    }
  }
}
2022-12-15 08:21:04,829|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|671:r_get_dns| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/name-services/dns/?fields=**" dns info:[{'attempts': 1, 'domains': {'string': ['gdl.englab.netapp.com']}, 'is-tld-query-enabled': 'true', 'name-servers': {'ip-address': ['10.224.223.135']}, 'require-packet-query-match': 'true', 'require-source-address-match': 'true', 'timeout': '2', 'vserver-name': 'test-cluster-dns'}]
2022-12-15 08:21:04,859|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|699:r_get_ntp| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/cluster/ntp/servers/?fields=**" response: {
  "records": [
    {
      "server": "10.60.248.183",
      "version": "auto",
      "authentication_enabled": false,
      "_links": {
        "self": {
          "href": "/api/cluster/ntp/servers/10.60.248.183?fields=**"
        }
      }
    }
  ],
  "num_records": 1,
  "_links": {
    "self": {
      "href": "/api/cluster/ntp/servers/?fields=%2A%2A"
    }
  }
}
2022-12-15 08:21:04,861|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|707:r_get_ntp| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/cluster/ntp/servers/?fields=**" ntp_info:[{'is-authentication-enabled': False, 'server-name': '10.60.248.183', 'version': 'auto'}]
2022-12-15 08:21:04,862| INFO|29446|5127|logger.py|132|cluster.py|3348:patch_cluster_management_network| Cluster [test-cluster-dns]: cluster management network information refreshed
2022-12-15 08:21:04,896|DEBUG|29446|5127|logger.py|132|ZAPI.py|241:invoke|
API: "cluster-identity-get"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:21:04,898|DEBUG|29446|5127|logger.py|132|ClusterZapis.py|225:z_get_cluster_identity| Cluster [test-cluster-dns]: got cluster_identity: [{'cluster-contact': None, 'cluster-location': None, 'cluster-name': 'test-cluster-dns', 'cluster-serial-number': '1-80-000011', 'cluster-uuid': '22723022-70a5-11ed-a778-000c297a9d59', 'rdb-uuid': 'c05e814e-70a5-11ed-b3b9-00a0b8cbd853'}]
2022-12-15 08:21:14,699|DEBUG|29446|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:21:14,700|DEBUG|29446|0|coroutine.py|190|Registered Myself: current tasks [{140255093715288: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140255093715016: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2022-12-15 08:21:14,702| INFO|29446|5132|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message
2022-12-15 08:21:14,704| INFO|29446|5132|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message returned in 3ms with status HTTPStatus.OK (BA)
2022-12-15 08:21:22,090|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|908:r_system_cli_version| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/private/cli/version?node=*&fields=versions" response: {
  "error": {
    "message": "The value \"versions\" is invalid for field \"fields\" (<field,...>)",
    "code": "262197",
    "target": "fields"
  }
}
2022-12-15 08:21:25,560|ERROR|29446|5127|logger.py|132|ClusterRestApis.py|916:r_system_cli_version| Cluster [test-cluster-dns]: System CLI, failed to get version.
2022-12-15 08:21:35,936|ERROR|29446|5127|logger.py|132|ClusterRestApis.py|921:r_system_cli_version| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/private/cli/version?node=*&fields=versions" System CLI version REST exception: <SDOTAdminError(key="ONTAPSelectSysCLIVersionFailed", message="Failed to get ONTAP Select version. Reason: REST returned bad status 400: The value "versions" is invalid for field "fields" (<field,...>).")>
2022-12-15 08:21:45,092| INFO|29446|5127|logger.py|132|event.py|134:__init__| <Event(id=734, request_id='5127', time='2022-12-15 08:21:45.083367', evtype='ClusterIdentityRefreshFailed', category='cluster', level='Error', detail='ONTAPSelectSysCLIVersionFailed: Failed to get ONTAP Select version. Reason: <SDOTAdminError(key="ONTAPSelectSysCLIVersionFailed", message="Failed to get ONTAP Select version. Reason: REST returned bad status 400: The value "versions" is invalid for field "fields" (<field,...>).")>.')>
2022-12-15 08:21:45,093|DEBUG|29446|5127|job.py|364|Updated <Job (CLUSTER_REFRESH) running [id:6a04eeea-7c51-11ed-abd3-000c297a9d59 rid:5127 mod:2022-12-15 08:21:45.093219]> [failed:True] ONTAPSelectSysCLIVersionFailed: Failed to get ONTAP Select version. Reason: <SDOTAdminError(key="ONTAPSelectSysCLIVersionFailed", message="Failed to get ONTAP Select version. Reason: REST returned bad status 400: The value "versions" is invalid for field "fields" (<field,...>).")>.
2022-12-15 08:21:57,198|DEBUG|29446|0|coroutine.py|190|Registered Myself: current tasks [{140255093715288: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140255093715832: <CoroutineRecord (asynchronous.crontab:create_mediator) [ACTIVE]>}]
2022-12-15 08:21:57,205|DEBUG|29446|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:21:57,206|DEBUG|29446|0|coroutine.py|190|Registered Myself: current tasks [{140255093715288: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140255093715832: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2022-12-15 08:21:57,312| INFO|29446|5133|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message
2022-12-15 08:21:57,313| INFO|29446|5133|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message returned in 107ms with status HTTPStatus.OK (BA)
2022-12-15 08:21:59,385|DEBUG|29446|5127|logger.py|132|ClusterRestApis.py|908:r_system_cli_version| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/private/cli/version?node=*&fields=versions" response: {
  "error": {
    "message": "The value \"versions\" is invalid for field \"fields\" (<field,...>)",
    "code": "262197",
    "target": "fields"
  }
}
2022-12-15 08:22:00,824|ERROR|29446|5127|logger.py|132|ClusterRestApis.py|916:r_system_cli_version| Cluster [test-cluster-dns]: System CLI, failed to get version.
2022-12-15 08:22:05,193|ERROR|29446|5127|logger.py|132|ClusterRestApis.py|921:r_system_cli_version| Cluster [test-cluster-dns]: "GET https://10.232.27.158:443/api/private/cli/version?node=*&fields=versions" System CLI version REST exception: <SDOTAdminError(key="ONTAPSelectSysCLIVersionFailed", message="Failed to get ONTAP Select version. Reason: REST returned bad status 400: The value "versions" is invalid for field "fields" (<field,...>).")>
2022-12-15 08:22:07,897| INFO|29446|5127|logger.py|132|event.py|134:__init__| <Event(id=735, request_id='5127', time='2022-12-15 08:22:07.891256', evtype='ClusterImageVersionRefreshFailed', category='cluster', level='Error', detail='ONTAPSelectSysCLIVersionFailed: Failed to get ONTAP Select version. Reason: <SDOTAdminError(key="ONTAPSelectSysCLIVersionFailed", message="Failed to get ONTAP Select version. Reason: REST returned bad status 400: The value "versions" is invalid for field "fields" (<field,...>).")>.')>
2022-12-15 08:22:07,898|DEBUG|29446|5127|job.py|364|Updated <Job (CLUSTER_REFRESH) running [id:6a04eeea-7c51-11ed-abd3-000c297a9d59 rid:5127 mod:2022-12-15 08:22:07.898569]> [failed:True] ONTAPSelectSysCLIVersionFailed: Failed to get ONTAP Select version. Reason: <SDOTAdminError(key="ONTAPSelectSysCLIVersionFailed", message="Failed to get ONTAP Select version. Reason: REST returned bad status 400: The value "versions" is invalid for field "fields" (<field,...>).")>.
2022-12-15 08:22:07,918|DEBUG|29446|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:22:07,918|DEBUG|29446|0|coroutine.py|190|Registered Myself: current tasks [{140255093715288: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140255093715832: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2022-12-15 08:22:07,919| INFO|29446|5134|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message
2022-12-15 08:22:07,921| INFO|29446|5134|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message returned in 3ms with status HTTPStatus.OK (BA)
2022-12-15 08:22:07,949| INFO|29446|5127|logger.py|132|ZAPI.py|241:invoke|
API: "system-get-version"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:22:07,951|DEBUG|29446|5127|logger.py|132|ClusterZapis.py|846:z_system_get_version| Cluster [test-cluster-dns]: system get version {'generation': '9', 'major': '13', 'minor': '0'}
2022-12-15 08:22:07,964|DEBUG|29446|5127|fault.py|147|Unable to find a registered fault for zapi.system_node_get_iter.
2022-12-15 08:22:07,986|DEBUG|29446|5127|logger.py|132|ZAPI.py|241:invoke|
API: "system-node-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:22:07,988|DEBUG|29446|5127|logger.py|132|ClusterZapis.py|245:z_system_node_get_iter| Cluster [test-cluster-dns]: got system node get iter: [[{'cpu-busytime': '516', 'env-failed-fan-count': '0', 'env-failed-fan-message': 'There are no failed fans.', 'env-failed-power-supply-count': '0', 'env-failed-power-supply-message': 'There are no failed power supplies.', 'env-over-temperature': 'false', 'is-all-flash-optimized': 'false', 'is-all-flash-select-optimized': 'false', 'is-capacity-optimized': 'false', 'is-cloud-optimized': 'false', 'is-diff-svcs': 'false', 'is-epsilon-node': 'true', 'is-node-cluster-eligible': 'true', 'is-node-healthy': 'true', 'is-perf-optimized': 'false', 'maximum-aggregate-size': '219902325555200', 'maximum-number-of-volumes': '1000', 'maximum-volume-size': '329853488332800', 'node': 'test-cluster-dns-01', 'node-location': None, 'node-model': 'FDvM300', 'node-nvram-id': '2443885337', 'node-owner': None, 'node-serial-number': '99887766554433221125', 'node-storage-configuration': 'unknown', 'node-system-id': '2443885337', 'node-uptime': '17426', 'node-uuid': '2273752c-70a5-11ed-a778-000c297a9d59', 'node-vendor': 'NetApp', 'nvram-battery-status': 'battery_ok', 'product-version': 'NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022', 'sas2-sas3-mixed-stack-support': 'none', 'vmhost-info': {'vm-uuid': '42163f4e-cda3-f86d-770f-fb7b9a23caa6', 'vmhost-error': 'Failed to connnect to the vSphere server. Reason: Either the server hostname or IP address is not set, or there are network issues. Correct the vSphere credentials with the "system node virtual-machine hypervisor modify-credentials" command.', 'vmhost-hardware-vendor': 'VMware, Inc.', 'vmhost-model': 'VMware Virtual Platform', 'vmhost-software-vendor': 'NetApp'}}]]
2022-12-15 08:22:07,993| INFO|29446|5127|logger.py|132|node.py|3480:patch_node_identity| Node [test-cluster-dns-01] Cluster [test-cluster-dns]: node identity refreshed
2022-12-15 08:22:08,031|DEBUG|29446|5127|logger.py|132|ZAPI.py|241:invoke|
API: "net-interface-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2022-12-15 08:22:08,033| INFO|29446|5127|logger.py|132|node.py|3386:patch_node_management_network| Node [test-cluster-dns-01] Cluster [test-cluster-dns]: node management network information refreshed
2022-12-15 08:22:08,039|DEBUG|29446|5127|logger.py|132|client_api_helper.py|221:get_vm_info| get_vm_info executing
2022-12-15 08:22:08,301|DEBUG|29446|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:22:08,302|DEBUG|29446|0|coroutine.py|190|Registered Myself: current tasks [{140255093715288: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140255093715832: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2022-12-15 08:22:08,306| INFO|29446|5135|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message
2022-12-15 08:22:08,308| INFO|29446|5135|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/6a04eeea-7c51-11ed-abd3-000c297a9d59?fields=*,last_modified,message returned in 6ms with status HTTPStatus.OK (BA)
2022-12-15 08:22:08,313|DEBUG|29446|5127|rest.py|173|response body: {"cpus":"4","host_id":"sdot-smicro-009.gdl.englab.netapp.com","hw_version":"vmx-14","memory":"16384","metadata":{"cluster_uuid":"22723022-70a5-11ed-a778-000c297a9d59","node_uuid":"2273752c-70a5-11ed-a778-000c297a9d59"},"mgmt_server_uid":"3025b4b7-b510-4852-98ed-38668b194b85","name":"test-cluster-dns-01","obj_id":"vm-8784","state":"poweredon","vm_uid":"5016667c-c755-52e8-d65c-e7bc43af8405"}
2022-12-15 08:22:08,315| INFO|29446|5127|logger.py|132|node.py|3568:refresh_vm_name| Node [test-cluster-dns-01] Cluster [test-cluster-dns]: Node vm_name information refresh successful.
2022-12-15 08:22:08,316|DEBUG|29446|5127|logger.py|132|client_api_helper.py|221:get_vm_info| get_vm_info executing
2022-12-15 08:22:08,565|DEBUG|29446|5127|rest.py|173|response body: {"cpus":"4","host_id":"sdot-smicro-009.gdl.englab.netapp.com","hw_version":"vmx-14","memory":"16384","metadata":{"cluster_uuid":"22723022-70a5-11ed-a778-000c297a9d59","node_uuid":"2273752c-70a5-11ed-a778-000c297a9d59"},"mgmt_server_uid":"3025b4b7-b510-4852-98ed-38668b194b85","name":"test-cluster-dns-01","obj_id":"vm-8784","state":"poweredon","vm_uid":"5016667c-c755-52e8-d65c-e7bc43af8405"}
2022-12-15 08:22:08,567| INFO|29446|5127|logger.py|132|node.py|3601:refresh_state| Node [test-cluster-dns-01] Cluster [test-cluster-dns]: Node state information refresh successful.
2022-12-15 08:22:08,568|DEBUG|29446|5127|logger.py|132|client_api_helper.py|558:vm_get_vm_vnics| vm_get_vm_vnics executing
2022-12-15 08:22:08,613|DEBUG|29446|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2022-12-15 08:22:08,614|DEBUG|29446|0|coroutine.py|190|Registered Myself: current tasks [{140255093715288: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140255093715832: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
