<suppressed/>
2023-01-02 05:56:51,107| INFO|17788|6130|logger.py|132|cluster.py|3351:patch_cluster_management_network| Cluster [ArunS_2node]: cluster management network information refreshed
2023-01-02 05:56:58,877|DEBUG|17788|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2023-01-02 05:56:58,879|DEBUG|17788|0|coroutine.py|190|Registered Myself: current tasks [{140069692031320: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140069692031592: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2023-01-02 05:56:58,881| INFO|17788|6138|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message
2023-01-02 05:56:58,884| INFO|17788|6138|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message returned in 4ms with status HTTPStatus.OK (BA)
2023-01-02 05:56:58,913| INFO|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "system-cli"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:47,168|ERROR|17788|6130|logger.py|132|ClusterZapis.py|1036:z_system_cli_set_disk_autoassign| Cluster [ArunS_2node]: The CLI command "storage disk option modify -autoassign off" failed: Error: command failed: Option "-autoassign" is not supported on this platform.
2023-01-02 05:57:58,983|DEBUG|17788|6130|fault.py|147|Unable to find a registered fault for zapi.system_node_get_iter.
2023-01-02 05:57:58,999|DEBUG|17788|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2023-01-02 05:57:59,000|DEBUG|17788|0|coroutine.py|190|Registered Myself: current tasks [{140069692031320: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140069701122520: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2023-01-02 05:57:59,002| INFO|17788|6139|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message
2023-01-02 05:57:59,004| INFO|17788|6139|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message returned in 4ms with status HTTPStatus.OK (BA)
2023-01-02 05:57:59,068|DEBUG|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "system-node-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:59,069|DEBUG|17788|6130|logger.py|132|ClusterZapis.py|245:z_system_node_get_iter| Cluster [ArunS_2node]: got system node get iter: [[{'cpu-busytime': '63790', 'env-failed-fan-count': '0', 'env-failed-fan-message': 'There are no failed fans.', 'env-failed-power-supply-count': '0', 'env-failed-power-supply-message': 'There are no failed power supplies.', 'env-over-temperature': 'false', 'is-all-flash-optimized': 'false', 'is-all-flash-select-optimized': 'false', 'is-capacity-optimized': 'false', 'is-cloud-optimized': 'false', 'is-diff-svcs': 'false', 'is-epsilon-node': 'false', 'is-node-cluster-eligible': 'true', 'is-node-healthy': 'true', 'is-perf-optimized': 'false', 'maximum-aggregate-size': '219902325555200', 'maximum-number-of-volumes': '1000', 'maximum-volume-size': '329853488332800', 'node': 'ArunS_2node-01', 'node-location': None, 'node-model': 'FDvM300', 'node-nvram-id': '2443885398', 'node-owner': None, 'node-serial-number': '99887766554433221186', 'node-storage-configuration': 'unknown', 'node-system-id': '2443885398', 'node-uptime': '1543988', 'node-uuid': 'b2c64bbe-63cf-11ed-bfb4-000c297a9d59', 'node-vendor': 'NetApp', 'nvram-battery-status': 'battery_ok', 'product-version': 'NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022', 'sas2-sas3-mixed-stack-support': 'none', 'vmhost-info': {'vm-uuid': '421698eb-a3ce-06c1-bee5-35bd3223040b', 'vmhost-error': 'Failed to connnect to the vSphere server. Reason: Either the server hostname or IP address is not set, or there are network issues. Correct the vSphere credentials with the "system node virtual-machine hypervisor modify-credentials" command.', 'vmhost-hardware-vendor': 'VMware, Inc.', 'vmhost-model': 'VMware Virtual Platform', 'vmhost-software-vendor': 'NetApp'}}, {'cpu-busytime': '63872', 'env-failed-fan-count': '0', 'env-failed-fan-message': 'There are no failed fans.', 'env-failed-power-supply-count': '0', 'env-failed-power-supply-message': 'There are no failed power supplies.', 'env-over-temperature': 'false', 'is-all-flash-optimized': 'false', 'is-all-flash-select-optimized': 'false', 'is-capacity-optimized': 'false', 'is-cloud-optimized': 'false', 'is-diff-svcs': 'false', 'is-epsilon-node': 'false', 'is-node-cluster-eligible': 'true', 'is-node-healthy': 'true', 'is-perf-optimized': 'false', 'maximum-aggregate-size': '219902325555200', 'maximum-number-of-volumes': '1000', 'maximum-volume-size': '329853488332800', 'node': 'ArunS_2node-02', 'node-location': None, 'node-model': 'FDvM300', 'node-nvram-id': '2443885326', 'node-owner': None, 'node-serial-number': '99887766554433221114', 'node-storage-configuration': 'unknown', 'node-system-id': '2443885326', 'node-uptime': '1543986', 'node-uuid': 'b2c71008-63cf-11ed-bfb4-000c297a9d59', 'node-vendor': 'NetApp', 'nvram-battery-status': 'battery_ok', 'product-version': 'NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022', 'sas2-sas3-mixed-stack-support': 'none', 'vmhost-info': {'vm-uuid': '42166123-d608-4c8e-9088-9b5e7ac95b09', 'vmhost-error': 'Failed to connnect to the vSphere server. Reason: Either the server hostname or IP address is not set, or there are network issues. Correct the vSphere credentials with the "system node virtual-machine hypervisor modify-credentials" command.', 'vmhost-hardware-vendor': 'VMware, Inc.', 'vmhost-model': 'VMware Virtual Platform', 'vmhost-software-vendor': 'NetApp'}}]]
2023-01-02 05:57:59,090|DEBUG|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "cluster-identity-get"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:59,091|DEBUG|17788|6130|logger.py|132|ClusterZapis.py|225:z_get_cluster_identity| Cluster [ArunS_2node]: got cluster_identity: [{'cluster-contact': None, 'cluster-location': None, 'cluster-name': 'ArunS_2node', 'cluster-serial-number': '1-80-000011', 'cluster-uuid': 'b2c5f3e4-63cf-11ed-bfb4-000c297a9d59', 'rdb-uuid': 'd368ce93-63d0-11ed-910c-00a0b8cba9da'}]
2023-01-02 05:57:59,092| INFO|17788|6130|logger.py|132|cluster.py|3517:patch_cluster_identity| Cluster [ArunS_2node]: cluster's node count validation successful
2023-01-02 05:57:59,094| INFO|17788|6130|logger.py|132|cluster.py|3528:patch_cluster_identity| Cluster [ArunS_2node]: cluster identity refreshed
2023-01-02 05:57:59,214| INFO|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "system-cli"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:59,215|DEBUG|17788|6130|logger.py|132|ClusterZapis.py|930:z_system_cli_version| Cluster [ArunS_2node]: System CLI, version: 2 entries were acted on.

Node: ArunS_2node-01
NetApp Release devN_221108_0200: Tue Nov  8 02:42:19 EST 2022   <1>

Node: ArunS_2node-02
NetApp Release devN_221108_0200: Tue Nov  8 02:42:19 EST 2022   <1>
2023-01-02 05:57:59,244| INFO|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "system-get-version"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:59,247|DEBUG|17788|6130|logger.py|132|ClusterZapis.py|846:z_system_get_version| Cluster [ArunS_2node]: system get version {'generation': '9', 'major': '13', 'minor': '0'}
2023-01-02 05:57:59,259|DEBUG|17788|6130|fault.py|147|Unable to find a registered fault for zapi.system_node_get_iter.
2023-01-02 05:57:59,289|DEBUG|17788|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2023-01-02 05:57:59,290|DEBUG|17788|0|coroutine.py|190|Registered Myself: current tasks [{140069692031320: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140069701122520: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2023-01-02 05:57:59,292| INFO|17788|6140|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message
2023-01-02 05:57:59,293| INFO|17788|6140|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message returned in 3ms with status HTTPStatus.OK (BA)
2023-01-02 05:57:59,324|DEBUG|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "system-node-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:59,327|DEBUG|17788|6130|logger.py|132|ClusterZapis.py|245:z_system_node_get_iter| Cluster [ArunS_2node]: got system node get iter: [[{'cpu-busytime': '63791', 'env-failed-fan-count': '0', 'env-failed-fan-message': 'There are no failed fans.', 'env-failed-power-supply-count': '0', 'env-failed-power-supply-message': 'There are no failed power supplies.', 'env-over-temperature': 'false', 'is-all-flash-optimized': 'false', 'is-all-flash-select-optimized': 'false', 'is-capacity-optimized': 'false', 'is-cloud-optimized': 'false', 'is-diff-svcs': 'false', 'is-epsilon-node': 'false', 'is-node-cluster-eligible': 'true', 'is-node-healthy': 'true', 'is-perf-optimized': 'false', 'maximum-aggregate-size': '219902325555200', 'maximum-number-of-volumes': '1000', 'maximum-volume-size': '329853488332800', 'node': 'ArunS_2node-01', 'node-location': None, 'node-model': 'FDvM300', 'node-nvram-id': '2443885398', 'node-owner': None, 'node-serial-number': '99887766554433221186', 'node-storage-configuration': 'unknown', 'node-system-id': '2443885398', 'node-uptime': '1543989', 'node-uuid': 'b2c64bbe-63cf-11ed-bfb4-000c297a9d59', 'node-vendor': 'NetApp', 'nvram-battery-status': 'battery_ok', 'product-version': 'NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022', 'sas2-sas3-mixed-stack-support': 'none', 'vmhost-info': {'vm-uuid': '421698eb-a3ce-06c1-bee5-35bd3223040b', 'vmhost-error': 'Failed to connnect to the vSphere server. Reason: Either the server hostname or IP address is not set, or there are network issues. Correct the vSphere credentials with the "system node virtual-machine hypervisor modify-credentials" command.', 'vmhost-hardware-vendor': 'VMware, Inc.', 'vmhost-model': 'VMware Virtual Platform', 'vmhost-software-vendor': 'NetApp'}}, {'cpu-busytime': '63872', 'env-failed-fan-count': '0', 'env-failed-fan-message': 'There are no failed fans.', 'env-failed-power-supply-count': '0', 'env-failed-power-supply-message': 'There are no failed power supplies.', 'env-over-temperature': 'false', 'is-all-flash-optimized': 'false', 'is-all-flash-select-optimized': 'false', 'is-capacity-optimized': 'false', 'is-cloud-optimized': 'false', 'is-diff-svcs': 'false', 'is-epsilon-node': 'false', 'is-node-cluster-eligible': 'true', 'is-node-healthy': 'true', 'is-perf-optimized': 'false', 'maximum-aggregate-size': '219902325555200', 'maximum-number-of-volumes': '1000', 'maximum-volume-size': '329853488332800', 'node': 'ArunS_2node-02', 'node-location': None, 'node-model': 'FDvM300', 'node-nvram-id': '2443885326', 'node-owner': None, 'node-serial-number': '99887766554433221114', 'node-storage-configuration': 'unknown', 'node-system-id': '2443885326', 'node-uptime': '1543987', 'node-uuid': 'b2c71008-63cf-11ed-bfb4-000c297a9d59', 'node-vendor': 'NetApp', 'nvram-battery-status': 'battery_ok', 'product-version': 'NetApp Release Lighthouse__9.13.0: Tue Nov 08 07:42:19 UTC 2022', 'sas2-sas3-mixed-stack-support': 'none', 'vmhost-info': {'vm-uuid': '42166123-d608-4c8e-9088-9b5e7ac95b09', 'vmhost-error': 'Failed to connnect to the vSphere server. Reason: Either the server hostname or IP address is not set, or there are network issues. Correct the vSphere credentials with the "system node virtual-machine hypervisor modify-credentials" command.', 'vmhost-hardware-vendor': 'VMware, Inc.', 'vmhost-model': 'VMware Virtual Platform', 'vmhost-software-vendor': 'NetApp'}}]]
2023-01-02 05:57:59,331| INFO|17788|6130|logger.py|132|node.py|3481:patch_node_identity| Node [ArunS_2node-01] Cluster [ArunS_2node]: node identity refreshed
2023-01-02 05:57:59,389|DEBUG|17788|6130|logger.py|132|ZAPI.py|241:invoke|
API: "net-interface-get-iter"
User: "admin"
Request:
<suppressed/>
Response:
<suppressed/>
2023-01-02 05:57:59,392| INFO|17788|6130|logger.py|132|node.py|3387:patch_node_management_network| Node [ArunS_2node-01] Cluster [ArunS_2node]: node management network information refreshed
2023-01-02 05:57:59,397|DEBUG|17788|6130|logger.py|132|client_api_helper.py|221:get_vm_info| get_vm_info executing
2023-01-02 05:57:59,592|DEBUG|17788|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2023-01-02 05:57:59,597|DEBUG|17788|0|coroutine.py|190|Registered Myself: current tasks [{140069692031320: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140069701122520: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2023-01-02 05:57:59,599| INFO|17788|6141|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message
2023-01-02 05:57:59,601| INFO|17788|6141|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message returned in 3ms with status HTTPStatus.OK (BA)
2023-01-02 05:57:59,647|DEBUG|17788|6130|rest.py|173|response body: {"cpus":"4","host_id":"sdot-smicro-009.gdl.englab.netapp.com","hw_version":"vmx-14","memory":"16384","metadata":{"cluster_uuid":"b2c5f3e4-63cf-11ed-bfb4-000c297a9d59","node_uuid":"b2c64bbe-63cf-11ed-bfb4-000c297a9d59"},"mgmt_server_uid":"3025b4b7-b510-4852-98ed-38668b194b85","name":"ArunS_2node-01","obj_id":"vm-8356","state":"poweredon","vm_uid":"5016cfce-cb7f-9695-d0a1-3e1f94727ec1"}
2023-01-02 05:57:59,648| INFO|17788|6130|logger.py|132|node.py|3569:refresh_vm_name| Node [ArunS_2node-01] Cluster [ArunS_2node]: Node vm_name information refresh successful.
2023-01-02 05:57:59,650|DEBUG|17788|6130|logger.py|132|client_api_helper.py|221:get_vm_info| get_vm_info executing
2023-01-02 05:57:59,900|DEBUG|17788|0|coroutine.py|177|RESTAPI [controllers.job:get_job] executing
2023-01-02 05:57:59,901|DEBUG|17788|0|coroutine.py|190|Registered Myself: current tasks [{140069692031320: <CoroutineRecord (asynchronous.cluster_tasks:refresh_cluster) [ACTIVE]>, 140069701122520: <CoroutineRecord (controllers.job:get_job) [ACTIVE]>}]
2023-01-02 05:57:59,902| INFO|17788|6142|restapi.py|231|Processing GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message
2023-01-02 05:57:59,904| INFO|17788|6142|restapi.py|263|GET http://127.0.0.1:8080/api/v3/jobs/3ed02b80-8a62-11ed-b289-000c297a9d59?fields=*,last_modified,message returned in 3ms with status HTTPStatus.OK (BA)
2023-01-02 05:57:59,910|DEBUG|17788|6130|rest.py|173|response body: {"cpus":"4","host_id":"sdot-smicro-009.gdl.englab.netapp.com","hw_version":"vmx-14","memory":"16384","metadata":{"cluster_uuid":"b2c5f3e4-63cf-11ed-bfb4-000c297a9d59","node_uuid":"b2c64bbe-63cf-11ed-bfb4-000c297a9d59"},"mgmt_server_uid":"3025b4b7-b510-4852-98ed-38668b194b85","name":"ArunS_2node-01","obj_id":"vm-8356","state":"poweredon","vm_uid":"5016cfce-cb7f-9695-d0a1-3e1f94727ec1"}
2023-01-02 05:57:59,912| INFO|17788|6130|logger.py|132|node.py|3602:refresh_state| Node [ArunS_2node-01] Cluster [ArunS_2node]: Node state information refresh successful.
